### ISSUE TITLE
Revamp Stencil Documentation 

### ISSUE THREAD

**Issue by shivankurchavan** [SamagraX-Stencil/stencil#121]
Revamp Stencil Documentation.

Link - https://stencil.samagra.io/

### To Do
- [ ]  update the link in documentation ( in CLI -> steup ) which points to @soorajk1/stencil to @samagra/stencil - https://stencil.samagra.io/cli/installation

Note - This Issue will be updated over time and more todos will be added accordingly to revamp documentation.

**Comment by RiyaRaj28** [comment]
updated.
