### ISSUE TITLE
Stencil Base Project Cleanup

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#131]
## P0
- [x] General Cleanup
    - [x] Remove `startup.*.sh` - P0
    - [x] Remove `wait-for-it.sh` - P0

- [x] Dockerfiles - [Refer](https://github.com/Samagra-Development/VISTAAR/blob/main/Dockerfile)
    - [x] Remove `e2e.Dockerfile` - P0
    - [x] Rewrite the `Dockerfile` and `Dockerfile.devcontainer` - P0

- [ ] Docker Compose Setup
    - [ ] Remove docker compose from the root and move to `/services` - PO
    - [ ] Update `docker-start.sh`
    - [ ] Add relevant commands in `package.json`

- [x] Husky Updates
    - [x] Add command for checking, fixing code formatting in precommit hooks. - P0
    - [x] Run `build` script and make sure that the code is building
    - [x] Run tests

## P1
- [ ] Update the github action workflows to also run the formatter and linter

**Comment by shivankurchavan** [comment]
please assign it to me : )

**Comment by shivankurchavan** [comment]
PR - [#8 ](https://github.com/SamagraX-Stencil/schematics/pull/8)
