### ISSUE TITLE
update response formatting interceptor

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#141]

**Comment by techsavvyash** [comment]
@Savio629 to make the discussed changes.

Changes were:
- [ ] remove the top level `message` key
- [ ] remove teh `code` key from `error`
- [ ] `data` key should be the response of the service not the body of the POST request.

**Comment by Savio629** [comment]
#### @ GET('/')
![image](https://github.com/SamagraX-Stencil/stencil/assets/91362589/cab99b95-8cee-4b7d-9737-35dcbb7da171)
#### @ POST('/')
![image](https://github.com/SamagraX-Stencil/stencil/assets/91362589/8b058b21-45c9-4dfb-8362-61666af77fde)
#### @ POST('/') - with a error
![image](https://github.com/SamagraX-Stencil/stencil/assets/91362589/bdb425ec-f962-47f2-9662-593467beef8c)

**Comment by techsavvyash** [comment]
@techsavvyash has tested and updated this and will be merged to main for the next release.
