### ISSUE TITLE
[stencil] Remove SWC bundler error

### ISSUE THREAD

**Issue by RyanWalker277** [SamagraX-Stencil/stencil#33]
Realted PR: https://github.com/SamagraX-Stencil/stencil/pull/31

**Comment by techsavvyash** [comment]
Provide more description on the bug -- @RyanWalker277

**Comment by RyanWalker277** [comment]
I have raised a ticket on official nestjs github repo. Here is the [Link](https://github.com/nestjs/nest/issues/13010)

**Comment by techsavvyash** [comment]
Reply recieved from Kamil, this is a simply import path error. 
- I was not able to reproduce this
- However as pointed out by kamil the fix should be simply to change the import from `src/..` to relative style like  `../..`

I think can be closed out, need confirmation from @RyanWalker277
