### ISSUE TITLE
[stencil] [C4GT] Add support for bun

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil#4]
# Add Runtime Support for Bun in Stencil NestJS Project

## Description

With the integrated support for NestJS in Bun, the task is to extend the runtime options in Stencil. Users should have the flexibility to choose between two supported runtimes: NodeJS and BunJS.

### Goals

1. **Bun Runtime Integration:** Successfully integrate BunJS as a supported runtime in the Stencil NestJS project.

2. **User Runtime Selection:** Allow users to choose between the two supported runtimes (NodeJS and BunJS) for executing Stencil.

## Acceptance Criteria

1. **BunJS Integration:** Implement the necessary configurations and adjustments to seamlessly integrate BunJS as a runtime in the Stencil NestJS project.

2. **Runtime Selection:** Implement a user-friendly mechanism to select the desired runtime (NodeJS or BunJS) when running Stencil.

3. **Testing:** Ensure that both NodeJS and BunJS runtimes are functional and can successfully execute Stencilt.

4. **Documentation Update:** Provide comprehensive documentation on your work. Include it in the form of a READMe.md in your PR. It will be added to the official Stencil Docs

### Checklist (To be filled by the developer)

- [ ] Integrate BunJS as a supported runtime in the Stencil NestJS project.
- [ ] Implement a user-friendly mechanism for selecting runtimes.
- [ ] Test both NodeJS and BunJS runtimes to ensure functionality.
- [ ] Update documentation to include details about the new runtime options and selection process.

## Product Name 
Stencil

## Organisation Name
SamagraX

## Tech Skills Needed
Nodejs, Bun

## Mentors
@RyanWalker277  

## Complexity
Medium

## Category
Backend

## Sub Category
Nodejs

**Comment by techsavvyash** [comment]
https://dev.to/mourishitz/running-nestjs-server-with-bun-4cdl -- good reference

**Comment by Sandeep0306** [comment]
Hi, @RyanWalker277 I would like to work on this issue. Can you assign me?

**Comment by techsavvyash** [comment]
Hey @Sandeep0306, please go ahead and raise a PR for the issue. Assignment only comes once a draft PR has been raised.

**Comment by techsavvyash** [comment]
Hey @vsvishalsharma,
Thanks for sending in the PR for the linting ticket, have merged the both of them.
If you interested in adding support for bun in stencil, please go right ahead and raise a PR.

**Comment by vsvishalsharma** [comment]
@techsavvyash sir I was woking on this i added scripts to run bunjs in package.json file but i keep getting an error of file dist/main not found 
![screenshot-01](https://github.com/SamagraX-Stencil/stencil/assets/131687529/79157e41-d8aa-46b1-a5cf-d17dc5fea6a9)
![screenshot-02](https://github.com/SamagraX-Stencil/stencil/assets/131687529/8d49dc62-646a-4ad5-8a94-b6e5bf07e701)

**Comment by techsavvyash** [comment]
The files inside the packages folder are not meant to be ran via a start script, try running the samples with bun, then make the required changes in the schematics files and then to the CLI.

**Comment by Yash-Sajwan24** [comment]
@techsavvyash I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by techsavvyash** [comment]
Hey @Yash-Sajwan24, 
Please go ahead .

**Comment by Savio629** [comment]
I'm too interested on trying out this issue.
I'll try to open a draft pr

**Comment by Savio629** [comment]
Just to confirm 
We need to add bun at this phase, right?
![image](https://github.com/SamagraX-Stencil/stencil/assets/91362589/48dc25f9-374d-46be-a8f7-357af4de1bb9)

**Comment by techsavvyash** [comment]
Yes

**Comment by Savio629** [comment]
Support for Bun Integration Tracker
Ref link: https://github.com/SamagraX-Stencil/stencil/pull/86#issuecomment-1991489825

## Step 1: Test Stencil Components with BunJS
- [x] Integrate Stencil components into NestJS app running with Bun.
- [x] Test for compatibility issues with sample folder.

### (Not required)
##### Step 2: Plan of Action (POA) (If there is no error in Step 1 then we can skip step 2)
- [x] Compile a list of encountered compatibility issues.
- [x] Identify required changes in Stencil `packages->common` and schematics, project.
- [x] Implementation Changes in Schematic folder and other components


## Step 3 : Implementation Changes in Stencil-Cli
- [x] Implement Changes in `lib->package managers`
- [x] Implement a user-friendly mechanism for selecting runtimes.

## Step 4 : Documentation and Reporting
- [x] Document the integration process and changes made.
- [x] Update READMEs and relevant documentation.

**Comment by Savio629** [comment]
## Step 1: Test Stencil Components with BunJS
(Note: Same issue occurs with npm start too)

### 01-all-features 
(I think the issue is with .env although I followed the steps mentioned in the docs)
![01-terminal](https://github.com/SamagraX-Stencil/stencil/assets/91362589/9bd59752-8460-43a3-ba23-c7b924f520db)


### 02-monitoring 
(I don't know why this issue is occuring)
![02-terminal](https://github.com/SamagraX-Stencil/stencil/assets/91362589/fbe6d4e6-0208-440e-9a04-410f16845ec0)

### 03-response-formatting 
(works well)
![03-terminal](https://github.com/SamagraX-Stencil/stencil/assets/91362589/e6dee9a1-238a-4276-8071-918d6a4c2eb5)

### 04-logging
(works well)
![04-terminal](https://github.com/SamagraX-Stencil/stencil/assets/91362589/58a73f0c-ebfe-44f4-af3d-a829b257fb66)

### 05-temporal-package
(is there any other steps i need to follow before setting up temporal-package?)
![05-terminal](https://github.com/SamagraX-Stencil/stencil/assets/91362589/5fd311c5-32db-4156-8dd2-c28289f3ec19)

### 06-file-upload
(works well)
![06-term](https://github.com/SamagraX-Stencil/stencil/assets/91362589/5dd17337-ca3b-466f-9156-5178006dfa13)

**Comment by Savio629** [comment]
@techsavvyash 
If all the samples work well, do I require to test other components present in `common` folder and the `stemantic` project or just update the cli project?

**Comment by Savio629** [comment]
@techsavvyash 

So I updated the code under stencil-cli and tested it out, seems to work well 👍
If it looks good I'll open a pr for review....
###### (Tested on Gitpod)

![bun-test1](https://github.com/SamagraX-Stencil/stencil/assets/91362589/d1d1f84d-5438-4f57-a393-d14af0729acb)
![bun-test2](https://github.com/SamagraX-Stencil/stencil/assets/91362589/ab6bb0d9-3313-4b15-9ae7-078f22828f98)
![bun-test3](https://github.com/SamagraX-Stencil/stencil/assets/91362589/18188bf6-28ec-4d5b-ace6-90490eb67bdb)

**Comment by techsavvyash** [comment]
Super work @Savio629 !!
Impressed by the turn around time. Yes please go ahead and raise a PR.
