### ISSUE TITLE
[Stencil UI] Setup Basic Design System

### ISSUE THREAD

**Issue by geeky-abhishek** [SamagraX-Stencil/stencil#53]
Set up the repository and establish the basic structure for the Design System.
- [ ] Theme
     - [x] Theme Provider
     - [x] Sizes
     - [ ] Spacing
     - [ ] Colour Code
- [ ] Components
     - [ ] Basic
          - [x] Button  
          - [x] Avatar
          - [ ] Icon
          - [x] Spinner
          - [x] Text
    - [ ] Display
         - [ ] Table  
         - [ ] List
         - [ ] DataList
     - [ ] Layout
          - [x] Container
          - [x] Row
          - [x] Divider
          - [x] Padding
          - [x] Paragraph
          - [ ] Card
     - [ ] Inputs
          - [x] Text Input
          - [x] Password Input
          - [x] Radio
          - [x] Radio Group
          - [x] Search
          - [x] Checkbox
          - [ ] Select
          - [ ] Dropdown
          - [ ] Datepicker
          - [ ] Timepicker
     - [ ] Feedback
          - [x] Toast 
          - [ ] Modal

**Comment by geeky-abhishek** [comment]
[stencil-ui.vercel.app](https://stencil-ui.vercel.app/)

**Comment by karntrehan** [comment]
Abhishek spoke to Om. @karntrehan to start conversation with design team to take this further.

**Comment by karntrehan** [comment]
Discussion undertaken with Design team. Design team mentioned using Material UI for atoms and creating components instead which would be used across apps. 

Followup meetings to be undertaken weekly on Friday.

**Comment by geeky-abhishek** [comment]
Design team ask to pick this up later
